providers:
  - name: StripeMock
    currencies: [USD, EUR]
    countries: [US, GB, DE]
    networks: [VISA, MASTERCARD]
    baseFeeBps: 300
  - name: AdyenMock
    currencies: [USD, EUR, GBP]
    countries: [US, NL, GB, DE]
    networks: [VISA, MASTERCARD, AMEX]
    baseFeeBps: 290
  - name: LocalBankMock
    currencies: [USD]
    countries: [US]
    networks: [VISA, MASTERCARD]
    baseFeeBps: 220

routing:
  # Active routing profile - can be changed at runtime
  profile: "balanced"  # Options: cost_optimized, rules_only, reliability_focused, balanced, etc.

  rules:
    - if: { country: US, network: AMEX }
      action: { prefer: [AdyenMock], mode: PREFERRED }
    - if: { binRange: "411111-411119" }
      action: { prefer: [LocalBankMock], mode: STRICT }
  strategies: { cost: true, weight: true, health: true }
  weights: { StripeMock: 60, AdyenMock: 30, LocalBankMock: 10 }

  # Custom routing profiles (optional - built-in profiles are always available)
  profiles:
    # Example custom profile for merchant-specific optimization
    merchant_optimized:
      strategies: ["rules", "cost"]
      weights:
        rules: 0.7
        cost: 0.3

    # Example high-volume profile for load balancing
    high_volume:
      strategies: ["load_balancing", "success_rate", "cost"]
      weights:
        load_balancing: 0.5
        success_rate: 0.3
        cost: 0.2

fx:
  rates:
    - { from: USD, to: EUR, rate: 0.90 }
    - { from: EUR, to: USD, rate: 1.11 }
    - { from: USD, to: GBP, rate: 0.78 }
